[package]
name = "email-sender-rust"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1

[dependencies]
actix-cors = "0.6.4"
actix-web = "4.2.1"
derive_more = "0.99.17"
dotenvy = "0.15.6"
env_logger = "0.9.3"
log = "0.4.17"
sendgrid_thin = "0.1.7"
sentry = "0.28.0"
serde = { version = "1.0.147", features = ["derive"] }
